meta_product_name: "My Emerald"
meta_title: "My Emerald | Owners App"
meta_description: "Making your Emerald experience simple and enjoyable"
meta_image: "https://res.cloudinary.com/emeraldstay/image/upload/v1553196565/OG.jpg"

